// ** Do not edit **
// generated by gen_hm-conf_banban-fetch-typescript.py 2024/02/14 09:22:34

import {is_local} from "./conf.ts";
export const Sanitizer_Allow_Tags = ["a", "abbr", "blockquote", "b", "br", "button", "caption", "code", "dl", "dt", "dd", "div", "em", "font", "h1", "h2", "h3", "h4", "h5", "h6", "hr", "i", "iframe", "img", "li", "nl", "ol", "picture", "pre", "p", "span", "source", "strike", "strong", "table", "thead", "tbody", "tr", "th", "td", "u", "ul", "video"]

export const Sanitizer_Allow_Attributes = {"*": ["class", "style", "color", "alt"], "a": ["route-href", "href", "target"], "button": ["md-button"], "font": ["face"], "img": ["src", "alt", "srcset", "data-a-dynamic-image"], "source": ["media", "type", "srcset"], "iframe": ["frameborder", "src", "width", "height", "class"], "u": []}

export const Auth_Issuer = is_local ? "https://ppa-aikawa.peace-and-passion.com:50020/":"https://auth.request.land/"

export const Auth_JWKs_URL = Auth_Issuer + "/.well-known/jwks.json"

export const Auth_JWKs_Cache_Expiration = 60
